---
- name: Provision Node
  hosts: "{{ hosts }}"
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Add node.js PPA
      sudo: true
      shell: curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -

    - name: Install Required Packages
      sudo: true
      apt:
        update_cache: true
        pkg: "{{ item }}"
        state: present
      with_items:
        - wget
        - nodejs
        - supervisor
        - openjdk-7-jdk

    - name: Stop service
      sudo: true
      supervisorctl: name="imply-{{node_type}}" state=stopped 

  roles:
    - imply
    - { role: imply-master, when: node_type == 'master' }
    - { role: imply-data, when: node_type == 'data' }
    - { role: imply-query, when: node_type == 'query' }

  post_tasks:
    - name: Reread supervisor
      sudo: true
      command: supervisorctl reread

    - name: Update supervisor
      sudo: true
      command: supervisorctl update

    - name: Restart service
      sudo: true
      supervisorctl: name="imply-{{node_type}}" state=restarted 
